Initial initialization fails when there are not enough resources
bitnami/bitnami-docker-minio pull request #67
Opened 2022-07-06 12:02 UTC by myback

Does not have time to launch in the background minio with limited container resources.  The error occurs at the stage: "Adding local Minio host to 'mc' configuration..." with message "Server not initialized, please try again".

Сan be reproduced: `docker run --cpus=".4" --rm -it bitnami/minio:2022.7.4-debian-11-r0`

2022-07-07 09:14 UTC, javsalgar commented
Hi,

Please note that our amd64 containers are not supported in M1 Macbooks. We are working on providing ARM containers but I cannot provide an ETA on this.

2022-07-07 09:39 UTC, myback commented
Hi,

I have the same error on x86. The first time we got this error was when deploying a large number of helm-releases to Kubernetes at the same time.

2022-07-11 11:00 UTC, javsalgar commented
Hi,

I tried reproducing the issue but I couldn't. Could you share extra steps to consistently reproduce the issue?

2022-07-13 11:18 UTC, javsalgar requested changes
Thank you! Small changes requested

2022-07-13 11:18 UTC, javsalgar commented on 2022/debian-11/rootfs/opt/bitnami/scripts/minio/setup.sh
> +        __data_drive="${drives[0]}"
For consistency, could you remove the `__` in front so it has the same naming as the rest of the variables?

2022-07-13 11:18 UTC, javsalgar commented on 2022/debian-11/rootfs/opt/bitnami/scripts/minio/setup.sh
> +    while ! minio_client_configure_local "${__data_drive:-MINIO_DATA_DIR}/.minio.sys/config/config.json"; do
We have a retry_while function that could work in this case, could you use it?

2022-07-20 10:51 UTC, javsalgar commented on 2022/debian-11/rootfs/opt/bitnami/scripts/minio/setup.sh
> +    retry_while "minio_client_configure_local ${data_drive:-MINIO_DATA_DIR}/.minio.sys/config/config.json"
In order to avoid a silent exit, could you add an if statement and add an error message?

2022-07-20 10:51 UTC, javsalgar commented on 2022/debian-11/rootfs/opt/bitnami/scripts/minio/setup.sh
> +    retry_while "minio_client_configure_local ${data_drive:-MINIO_DATA_DIR}/.minio.sys/config/config.json"
if ! retry_while ...; then
  error "<error message here>"
  exit 1
fi

2022-07-21 08:49 UTC, javsalgar approved these changes

2022-07-21 08:49 UTC, merged